---
name: Run tests

on:
  push:

  workflow_dispatch:

  pull_request:
jobs:
  test-components:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - component: "plugins/serverless-scheduler-html-checker"
            checkout_directory: "plugins/serverless-scheduler-html-checker"
            python-version: "3.9"
          - component: "plugins/serverless-scheduler-html-checker/serverless-scheduler-html-checker-api"
            checkout_directory: "plugins/serverless-scheduler-html-checker"
            python-version: "3.9"
    uses: ./.github/workflows/build-and-test-python.yml
    with:
      python-version: ${{ matrix.cfg.python-version }}
      directory: ${{ matrix.cfg.component }}
      checkout_directory: ${{ matrix.cfg.checkout_directory }}

  pre-commit:
    runs-on: ubuntu-latest
    env:
      tflint_version: v0.44.1

    steps:
      - uses: terraform-linters/setup-tflint@v3
        name: Setup TFLint
        #if: steps.cache-tflint.outputs.cache-hit != 'true'
        with:
          tflint_version: ${{ env.tflint_version }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0
